# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'os_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpenSphereWindow(object):
    def setupUi(self, OpenSphereWindow):
        OpenSphereWindow.setObjectName("OpenSphereWindow")
        OpenSphereWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        OpenSphereWindow.resize(1435, 1023)
        self.centralwidget = QtWidgets.QWidget(OpenSphereWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(240, 40, 1191, 801))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(540, 50, 321, 311))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 481, 331))
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 380, 481, 1))
        self.line.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 400, 481, 141))
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_2.setLineWidth(0)
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.versionLabel = QtWidgets.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(240, 10, 981, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.versionLabel.setFont(font)
        self.versionLabel.setObjectName("versionLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 850, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(10, 870, 1411, 101))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.treeWidget.setMidLineWidth(1)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setObjectName("treeWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vm_treeView = QtWidgets.QTreeView(self.centralwidget)
        self.vm_treeView.setGeometry(QtCore.QRect(10, 40, 221, 801))
        self.vm_treeView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.vm_treeView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.vm_treeView.setObjectName("vm_treeView")
        OpenSphereWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OpenSphereWindow)
        self.statusbar.setObjectName("statusbar")
        OpenSphereWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(OpenSphereWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1435, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuInventory = QtWidgets.QMenu(self.menubar)
        self.menuInventory.setObjectName("menuInventory")
        self.menuAdministration = QtWidgets.QMenu(self.menubar)
        self.menuAdministration.setObjectName("menuAdministration")
        self.menuExtras = QtWidgets.QMenu(self.menubar)
        self.menuExtras.setObjectName("menuExtras")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        OpenSphereWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuInventory.menuAction())
        self.menubar.addAction(self.menuAdministration.menuAction())
        self.menubar.addAction(self.menuExtras.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(OpenSphereWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenSphereWindow)

    def retranslateUi(self, OpenSphereWindow):
        _translate = QtCore.QCoreApplication.translate
        OpenSphereWindow.setWindowTitle(_translate("OpenSphereWindow", "OpenSphere"))
        self.label_2.setText(_translate("OpenSphereWindow", "<html><head/><body><p><img src=\":/images/images/getting-started.PNG\"/></p></body></html>"))
        self.textEdit.setHtml(_translate("OpenSphereWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">What is a Host?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">A host is a computer that uses virtualization software, suck as Xen or KVM, to run virtual machines. Hosts provide the CPU and memory resources that virtual machines use and give virtual machines access to storage and network connectivity.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">You can add a virtual machine to a host by creating a new one or deploying a glance image.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The easiest way to add a virtual machine is to deploy a Glance image. A Glance image is a pre-built virtual machine with an operating system and software already installed. A new virtual machine will need a new operating system installed on it, such as Linux, FreeBSD or UNIX.</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("OpenSphereWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Basic Tasks</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#55007f;\">&gt;  Deploy VM from a Glance Image</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; color:#55007f;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#55007f;\">&gt;  Create a new virtual machine</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OpenSphereWindow", "Getting Started"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OpenSphereWindow", "Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("OpenSphereWindow", "Virtual Machines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("OpenSphereWindow", "Resource Allocation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("OpenSphereWindow", "Performance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("OpenSphereWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("OpenSphereWindow", "Local Users & Groups"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("OpenSphereWindow", "Events"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("OpenSphereWindow", "Permissions"))
        self.versionLabel.setText(_translate("OpenSphereWindow", "[target-hostname] OpenSphere 0.0a build 1"))
        self.label_3.setText(_translate("OpenSphereWindow", "Recent Tasks"))
        self.treeWidget.headerItem().setText(0, _translate("OpenSphereWindow", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("OpenSphereWindow", "Target"))
        self.treeWidget.headerItem().setText(2, _translate("OpenSphereWindow", "Status"))
        self.treeWidget.headerItem().setText(3, _translate("OpenSphereWindow", "Details"))
        self.treeWidget.headerItem().setText(4, _translate("OpenSphereWindow", "Initiated by"))
        self.treeWidget.headerItem().setText(5, _translate("OpenSphereWindow", "Requested Start Time"))
        self.treeWidget.headerItem().setText(6, _translate("OpenSphereWindow", "Start Time"))
        self.treeWidget.headerItem().setText(7, _translate("OpenSphereWindow", "Completed Time"))
        self.label.setText(_translate("OpenSphereWindow", " VM Inventory:"))
        self.menuFile.setTitle(_translate("OpenSphereWindow", "File"))
        self.menuEdit.setTitle(_translate("OpenSphereWindow", "Edit"))
        self.menuView.setTitle(_translate("OpenSphereWindow", "View"))
        self.menuInventory.setTitle(_translate("OpenSphereWindow", "Inventory"))
        self.menuAdministration.setTitle(_translate("OpenSphereWindow", "Administration"))
        self.menuExtras.setTitle(_translate("OpenSphereWindow", "Extras"))
        self.menuHelp.setTitle(_translate("OpenSphereWindow", "Help"))

import OpenSphere_rc
